import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://pl.meghdo.com/login');
  await page.getByRole('button', { name: 'Customize' }).click();
  await page.locator('label').filter({ hasText: 'Analytics CookiesHelp us' }).click();
  await page.getByRole('checkbox', { name: 'Functional Cookies Remember' }).check();
  await page.getByRole('checkbox', { name: 'Marketing Cookies' }).check();
  await page.getByRole('button', { name: 'Save Preferences' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('shraddha@gmail.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Students@12345');
  await page.locator('iframe[src="https://challenges.cloudflare.com/cdn-cgi/challenge-platform/h/g/turnstile/f/ov2/av0/rch/56umw/0x4AAAAAACrWnV4vct-K6Bp1/auto/fbE/new/normal?lang=auto"]').contentFrame().locator('body').click();
  await page.getByRole('button', { name: 'Forgot password?' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('shraddha@gmail.com');
  await page.getByRole('button', { name: 'Send OTP' }).click();
  await page.getByRole('textbox', { name: 'OTP Code' }).fill('123456');
  await page.getByRole('button', { name: 'Verify OTP' }).click();
  await page.getByRole('button', { name: 'Profile menu for Shraddha' }).click();
  await page.getByRole('menuitem', { name: 'Profile' }).click();
  await page.getByRole('button', { name: 'Manage Subjects' }).click();
  await page.getByRole('button', { name: 'Go to Dashboard' }).click();
  await page.getByRole('button', { name: 'Add Bank Details' }).click();
  await page.getByRole('combobox').click();
  await page.getByRole('option', { name: 'Female' }).click();
  await page.getByRole('textbox', { name: 'Mailing Address (if different)' }).click();
  await page.getByRole('textbox', { name: 'Mailing Address (if different)' }).fill('Sanjana heights ');
  await page.getByText('French').click();
  await page.getByText('German').click();
  await page.getByRole('button', { name: 'Save Profile Changes' }).click();
  await page.getByRole('tab', { name: 'Professional' }).click();
  await page.getByRole('spinbutton', { name: 'Advance Booking Window (hours)' }).click();
  await page.getByRole('spinbutton', { name: 'Advance Booking Window (hours)' }).fill('');
  await page.getByRole('combobox').click();
  await page.getByRole('option', { name: 'Asia/Kolkata (IST)' }).click();
  await page.getByRole('switch', { name: 'Teacher Certified' }).click();
  await page.getByRole('switch', { name: 'Offer Free Trial Session' }).click();
  await page.getByRole('switch', { name: 'Allow Group Tuition' }).click();
  await page.getByRole('switch', { name: 'Enable Instant Booking' }).click();
  await page.getByRole('switch', { name: 'Ready to Teach Online' }).click();
  await page.getByRole('button', { name: 'Save Profile Changes' }).click();
  await page.getByRole('tab', { name: 'Education' }).click();
  await page.getByRole('button', { name: 'Save Profile Changes' }).click();
  await page.getByRole('tab', { name: 'Billing' }).click();
  await page.getByRole('combobox', { name: 'Country *' }).click();
  await page.getByRole('option', { name: '🇮🇳 India' }).click();
  await page.getByRole('textbox', { name: 'Account Holder Name *' }).click();
  await page.getByRole('textbox', { name: 'Account Holder Name *' }).fill('Shraddha akansha tiwari');
  await page.getByRole('textbox', { name: 'Account Number *' }).click();
  await page.getByRole('textbox', { name: 'Account Number *' }).fill('1234567890');
  await page.getByRole('textbox', { name: 'Bank Name *' }).click();
  await page.getByRole('textbox', { name: 'Bank Name *' }).fill('state bank of india ');
  await page.getByRole('textbox', { name: 'IFSC Code *' }).click();
  await page.getByRole('textbox', { name: 'IFSC Code *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'IFSC Code *' }).fill('SBIN0001234');
  await page.getByRole('combobox', { name: 'Account Type' }).click();
  await page.getByText('Current').click();
  await page.getByRole('button', { name: 'Save Bank Account' }).click();
  await page.getByRole('button', { name: 'Save Profile Changes' }).click();
  await page.getByRole('tab', { name: 'Security' }).click();
  await page.getByRole('button', { name: 'Profile menu for Shraddha' }).click();
  await page.getByRole('menuitem', { name: 'Profile' }).click();
  await page.getByRole('button', { name: 'Set Up Now' }).click();
  await page.getByRole('button', { name: 'Add Date' }).click();
  await page.getByRole('button', { name: 'Save One-time Availability' }).click();
  await page.getByRole('button', { name: 'Tue' }).click();
  await page.getByText('MonTueWedThuFriSatSun').click();
  await page.getByRole('button', { name: 'Add Time Slot' }).click();
  await page.locator('label').filter({ hasText: 'Sat' }).click();
  await page.locator('label').filter({ hasText: 'Fri' }).click();
  await page.getByRole('button', { name: 'Save & Publish Availability' }).click();
  await page.getByRole('button', { name: '11' }).nth(2).click();
  await page.getByRole('button', { name: '18', description: 'Toggle leave', exact: true }).click();
  await page.getByRole('button', { name: '20', description: 'Toggle leave', exact: true }).click();
  await page.getByRole('textbox', { name: 'e.g. Vacation, Medical,' }).click();
  await page.getByRole('textbox', { name: 'e.g. Vacation, Medical,' }).fill('FEVER');
  await page.getByRole('button', { name: 'Block 3 Days' }).click();
  await page.getByRole('button', { name: 'Services' }).click();
  await page.getByRole('button', { name: 'New Batch' }).click();
  await page.getByRole('combobox').first().selectOption('Wellness & Counselling');
  await page.getByRole('combobox').nth(1).selectOption('Intermediate');
  await page.getByRole('combobox').nth(2).selectOption('Career Counselling');
  await page.getByRole('button', { name: 'Full syllabus learning' }).click();
  await page.locator('label').filter({ hasText: 'Small Group Live (2–5)' }).click();
  await page.getByRole('textbox').fill('2026-06-05');
  await page.getByPlaceholder('e.g. 10').click();
  await page.getByPlaceholder('e.g. 10').fill('14');
  await page.getByPlaceholder('e.g. 5').click();
  await page.getByPlaceholder('e.g. 5').fill('5');
  await page.getByRole('button', { name: 'Fri' }).click();
  await page.getByRole('button', { name: 'Fri' }).click();
  await page.getByRole('button', { name: 'Sun' }).click();
  await page.getByRole('combobox').nth(4).selectOption('09:00-10:00');
  await page.getByRole('button', { name: 'Save as Draft & Next →' }).click();
  await page.getByRole('button', { name: 'New Service' }).click();
  await page.getByRole('combobox').selectOption('Pranic Healing');
  await page.getByRole('button', { name: 'Exam preparation' }).click();
  await page.getByRole('button', { name: 'Create Service' }).click();
  await page.getByRole('button', { name: 'Syllabus' }).first().click();
  await page.locator('div').filter({ hasText: /^1$/ }).first().click();
  await page.getByRole('textbox', { name: 'Session 1 topic…' }).fill('TOPIC SELECTION ');
  await page.getByRole('textbox', { name: 'Session 2 topic…' }).click();
  await page.getByRole('textbox', { name: 'Session 2 topic…' }).fill('TOPIC SELECTION ');
  await page.locator('div').filter({ hasText: /^3$/ }).first().click();
  await page.getByRole('textbox', { name: 'Session 3 topic…' }).fill('REVIEW');
  await page.locator('div').filter({ hasText: /^4$/ }).click();
  await page.getByRole('textbox', { name: 'Session 4 topic…' }).fill('REVIEW2');
  await page.locator('div').filter({ hasText: /^5$/ }).click();
  await page.getByRole('textbox', { name: 'Session 5 topic…' }).fill('EXAM ');
  await page.locator('div').filter({ hasText: /^6$/ }).click();
  await page.getByRole('textbox', { name: 'Session 6 topic…' }).fill('RESULTS ');
  await page.locator('div').filter({ hasText: /^7$/ }).click();
  await page.getByRole('textbox', { name: 'Session 7 topic…' }).fill('SMALL PRE TESTS ');
  await page.locator('div').filter({ hasText: /^8$/ }).click();
  await page.locator('div').filter({ hasText: /^8$/ }).click();
  await page.getByRole('textbox', { name: 'Session 8 topic…' }).fill('PREPARATIONS AGAIN ');
  await page.locator('div').filter({ hasText: /^9$/ }).click();
  await page.getByRole('textbox', { name: 'Session 9 topic…' }).fill('EVALUTION ');
  await page.locator('div').filter({ hasText: /^10$/ }).click();
  await page.getByRole('textbox', { name: 'Session 10 topic…' }).fill('FUNTIONALITY ');
  await page.locator('div').filter({ hasText: /^11$/ }).click();
  await page.getByRole('textbox', { name: 'Session 11 topic…' }).fill('END ');
  await page.locator('div').filter({ hasText: /^12$/ }).click();
  await page.getByRole('textbox', { name: 'Session 12 topic…' }).fill('END CREDITS ');
  await page.locator('div').filter({ hasText: /^13$/ }).click();
  await page.getByRole('textbox', { name: 'Session 13 topic…' }).fill('RESPONSE');
  await page.locator('div').filter({ hasText: /^14$/ }).click();
  await page.getByRole('textbox', { name: 'Session 14 topic…' }).fill('THANKS ');
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(2).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(4).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(5).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(3).click();
  await page.locator('.text-teal-500').first().click();
  await page.locator('.text-teal-500').first().click();
  await page.locator('.text-teal-500').first().click();
  await page.locator('.text-teal-500').first().click();
  await page.locator('.text-teal-500').first().click();
  await page.locator('.text-teal-500').first().click();
  await page.locator('.text-teal-500').first().click();
  await page.locator('.text-teal-500').first().click();
  await page.locator('.text-teal-500').first().click();
  await page.locator('.text-teal-500').click();
  await page.getByRole('button', { name: 'Save Syllabus' }).click();
  await page.getByRole('button', { name: 'Pricing' }).first().click();
  await page.getByPlaceholder('500').click();
  await page.getByPlaceholder('500').fill('500');
  await page.getByPlaceholder('30').click();
  await page.getByPlaceholder('30').fill('30');
  await page.getByPlaceholder('25').click();
  await page.getByPlaceholder('25').fill('25');
  await page.getByPlaceholder('28').click();
  await page.getByPlaceholder('28').fill('28');
  await page.getByPlaceholder('35').click();
  await page.getByPlaceholder('35').fill('35');
  await page.getByPlaceholder('32').click();
  await page.getByPlaceholder('32').fill('32');
  await page.getByRole('button', { name: 'Save Pricing' }).click();
  await page.getByRole('button', { name: 'Close panel' }).click();
  await page.getByRole('button', { name: 'Publish', exact: true }).click();
  await page.getByRole('button', { name: 'Yes, Publish' }).click();
  await page.getByRole('button', { name: 'Syllabus' }).click();
  await page.locator('.flex.flex-wrap').first().click();
  await page.getByRole('textbox', { name: 'Session 1 topic…' }).fill('TEACHING ');
  await page.getByRole('button', { name: 'Save Syllabus' }).click();
  await page.getByRole('button', { name: 'Pricing' }).first().click();
  await page.getByPlaceholder('500').click();
  await page.getByPlaceholder('500').fill('200');
  await page.getByPlaceholder('500').press('Tab');
  await page.getByPlaceholder('30').fill('15');
  await page.getByPlaceholder('30').press('Tab');
  await page.getByPlaceholder('25').fill('15');
  await page.getByPlaceholder('25').press('Tab');
  await page.getByPlaceholder('28').fill('15');
  await page.getByPlaceholder('28').press('Tab');
  await page.getByPlaceholder('35').fill('15');
  await page.getByPlaceholder('35').press('Tab');
  await page.getByPlaceholder('32').fill('15');
  await page.getByRole('button', { name: 'Save Pricing' }).click();
  await page.getByRole('button', { name: 'Availability' }).nth(2).click();
  await page.getByRole('button', { name: 'Map', description: 'Map to this service', exact: true }).click();
  await page.getByRole('button', { name: 'Close panel' }).click();
  await page.getByRole('button', { name: 'Publish', exact: true }).click();
  await page.getByRole('button', { name: 'Yes, Publish' }).click();
  await page.getByText('Syllabus').nth(4).click();
  await page.getByRole('button', { name: 'Dashboard' }).click();
});