import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://sat.meghdo.com/login');
  await page.getByRole('button', { name: 'Accept All' }).click();
  await page.getByRole('button', { name: 'Sign Up' }).click();
  await page.locator('label').filter({ hasText: 'Teach (Tutor)' }).click();
  await page.getByRole('combobox').nth(1).selectOption('Haryana');
  await page.getByRole('textbox', { name: 'e.g.' }).click();
  await page.getByRole('textbox', { name: 'e.g.' }).fill('40001');
  await page.getByPlaceholder('Enter your age').click();
  await page.getByPlaceholder('Enter your age').fill('34');
  await page.getByRole('checkbox', { name: 'I confirm that the' }).check();
  await page.getByRole('button', { name: 'Continue →' }).click();
  await page.getByRole('textbox', { name: 'you@example.com' }).click();
  await page.getByRole('textbox', { name: 'you@example.com' }).fill('mansi@gmail.com');
  await page.getByRole('button', { name: 'Send Verification Code' }).click();
  await page.getByRole('textbox', { name: '000000' }).click();
  await page.getByRole('textbox', { name: '000000' }).fill('123456');
  await page.getByRole('button', { name: 'Verify Code' }).click();
  await page.getByRole('textbox', { name: 'Jane' }).click();
  await page.getByRole('textbox', { name: 'Jane' }).fill('jane ');
  await page.getByRole('textbox', { name: 'Jane' }).press('Tab');
  await page.getByRole('textbox', { name: 'Doe' }).fill('doe ');
  await page.getByRole('textbox', { name: 'e.g. +' }).click();
  await page.getByRole('textbox', { name: 'e.g. +' }).fill('8591093626');
  await page.getByRole('textbox', { name: '••••••••' }).first().click();
  await page.getByRole('textbox', { name: '••••••••' }).first().fill('Students@12345');
  await page.getByRole('textbox', { name: '••••••••' }).nth(1).click();
  await page.getByRole('textbox', { name: '••••••••' }).nth(1).fill('Students@12345');
  await page.getByRole('button', { name: 'Create Account' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByRole('textbox', { name: 'First Name' }).fill('jane ');
  await page.getByRole('textbox', { name: 'Middle Name' }).click();
  await page.getByRole('textbox', { name: 'Middle Name' }).fill('doe ');
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).fill('doe ');
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByRole('textbox', { name: 'Last Name' }).fill('chen');
  await page.locator('input[type="date"]').fill('2008-06-03');
  await page.getByRole('combobox').first().selectOption('male');
  await page.getByRole('textbox', { name: 'Phone Number' }).click();
  await page.getByRole('textbox', { name: 'Phone Number' }).fill('8591093626');
  await page.getByRole('textbox', { name: 'Main St, Apt 4B' }).click();
  await page.getByRole('textbox', { name: 'Main St, Apt 4B' }).fill('123 main streets ');
  await page.locator('.react-select__input-container').click();
  await page.locator('#react-select-2-input').fill('mumbai');
  await page.getByRole('option', { name: 'Mumbai, Maharashtra' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
});