import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://pl.meghdo.com/login');
  await page.getByRole('button', { name: 'Customize' }).click();
  await page.getByRole('checkbox', { name: 'Analytics Cookies Help us' }).check();
  await page.getByRole('checkbox', { name: 'Functional Cookies Remember' }).check();
  await page.getByRole('checkbox', { name: 'Marketing Cookies' }).check();
  await page.getByRole('button', { name: 'Save Preferences' }).click();
  await page.getByRole('button', { name: 'Sign Up' }).click();
  await page.locator('label').filter({ hasText: 'Teach (Tutor)' }).click();
  await page.getByRole('combobox').nth(1).selectOption('Karnataka');
  await page.getByRole('textbox', { name: 'e.g.' }).click();
  await page.getByRole('textbox', { name: 'e.g.' }).fill('400060');
  await page.getByPlaceholder('Enter your age').click();
  await page.getByPlaceholder('Enter your age').fill('24');
  await page.locator('label').filter({ hasText: 'I confirm that the' }).click();
  await page.getByRole('button', { name: 'Continue →' }).click();
  await page.getByRole('textbox', { name: 'you@example.com' }).click();
  await page.getByRole('textbox', { name: 'you@example.com' }).fill('shraddha@gmail.com');
  await page.getByRole('button', { name: 'Send Verification Code' }).click();
  await page.getByRole('textbox', { name: '000000' }).click();
  await page.getByRole('textbox', { name: '000000' }).fill('123456');
  await page.getByRole('button', { name: 'Verify Code' }).click();
  await page.getByRole('textbox', { name: 'Jane' }).click();
  await page.getByRole('textbox', { name: 'Jane' }).fill('Shraddha');
  await page.getByRole('textbox', { name: 'Doe' }).click();
  await page.getByRole('textbox', { name: 'Doe' }).fill('Tiwari');
  await page.getByRole('textbox', { name: 'e.g. +' }).click();
  await page.getByRole('textbox', { name: 'e.g. +' }).fill('9619682969');
  await page.getByRole('textbox', { name: '••••••••' }).first().click();
  await page.getByRole('textbox', { name: '••••••••' }).first().fill('Students@12345');
  await page.getByRole('textbox', { name: '••••••••' }).nth(1).click();
  await page.getByRole('textbox', { name: '••••••••' }).nth(1).fill('Students@12345');
  await page.getByRole('button', { name: 'Create Account' }).click();
  await page.getByRole('textbox', { name: 'Middle Name' }).click();
  await page.getByRole('textbox', { name: 'Middle Name' }).fill('akansha');
  await page.locator('input[type="date"]').fill('2005-06-09');
  await page.getByRole('combobox').first().selectOption('male');
  await page.getByRole('textbox', { name: 'Phone Number' }).click();
  await page.getByRole('textbox', { name: 'Phone Number' }).fill('9619682969');
  await page.getByRole('textbox', { name: 'Main St, Apt 4B' }).click();
  await page.getByRole('textbox', { name: 'Main St, Apt 4B' }).fill('lal bahadur dubey building meghwadi jogeshwari (E)');
  await page.locator('.react-select__input-container').click();
  await page.locator('#react-select-2-input').fill('mum');
  await page.getByRole('option', { name: 'Mumbai, Maharashtra' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.locator('select').selectOption('undergraduate');
  await page.getByRole('textbox', { name: 'e.g. B.Sc, B.Ed, M.Tech' }).click();
  await page.getByRole('textbox', { name: 'e.g. B.Sc, B.Ed, M.Tech' }).fill('B.Ed');
  await page.locator('div').filter({ hasText: /^Search city\.\.\.$/ }).nth(4).click();
  await page.locator('#react-select-5-input').fill('mumbai');
  await page.getByRole('option', { name: 'Mumbai, Maharashtra' }).click();
  await page.locator('div').filter({ hasText: /^Search institute\.\.\.$/ }).nth(1).click();
  await page.locator('#react-select-8-input').fill('mumbai');
  await page.getByRole('option', { name: 'University of Mumbai (Mumbai)' }).click();
  await page.getByRole('button', { name: 'Yes, I am' }).click();
  await page.getByRole('textbox', { name: 'List other relevant' }).click();
  await page.getByRole('textbox', { name: 'List other relevant' }).fill('Microsoft verified educator ');
  await page.getByRole('button', { name: 'Add Experience' }).click();
  await page.getByRole('textbox', { name: 'e.g. DPS International or' }).click();
  await page.getByRole('textbox', { name: 'e.g. DPS International or' }).fill('BYJU\'S TUTOR ');
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').fill('02');
  await page.getByRole('textbox', { name: 'Briefly describe your overall' }).click();
  await page.getByRole('textbox', { name: 'Briefly describe your overall' }).click();
  await page.getByRole('textbox', { name: 'Briefly describe your overall' }).fill('i started my courer form undergraduate degree ');
  await page.locator('.css-18foq54-control > .css-hlgwow > .css-19bb58m').click();
  await page.locator('#react-select-4-input').fill('eng');
  await page.getByRole('option', { name: 'English' }).click();
  await page.getByRole('button', { name: 'Continue to Subjects →' }).click();
  await page.getByRole('combobox').filter({ hasText: 'Select Category' }).click();
  await page.getByRole('option', { name: 'Wellness & Counselling' }).click();
  await page.getByRole('button', { name: 'Pranic Healing' }).click();
  await page.getByRole('combobox').click();
  await page.getByRole('option', { name: 'Professional (3-5 years)' }).click();
  await page.getByRole('checkbox', { name: 'Beginner' }).click();
  await page.getByRole('checkbox', { name: 'All Levels' }).click();
  await page.getByRole('button', { name: 'Save Subject Setup' }).click();
  await page.getByRole('button', { name: 'Yoga Therapy' }).click();
  await page.getByRole('combobox').click();
  await page.getByText('Professional (3-5 years)').click();
  await page.getByRole('checkbox', { name: 'All Levels' }).click();
  await page.getByRole('button', { name: 'Save Subject Setup' }).click();
  await page.getByRole('button', { name: 'Life Coaching' }).click();
  await page.getByRole('checkbox', { name: 'All Levels' }).click();
  await page.getByRole('button', { name: 'Save Subject Setup' }).click();
  await page.getByRole('button', { name: 'Career Counselling' }).click();
  await page.getByRole('checkbox', { name: 'Intermediate' }).click();
  await page.getByRole('button', { name: 'Save Subject Setup' }).click();
  await page.getByRole('button', { name: 'Relationship Counselling' }).click();
  await page.getByRole('checkbox', { name: 'Advanced' }).click();
  await page.getByRole('button', { name: 'Save Subject Setup' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Middle School (6-8)' }).click();
  await page.getByRole('button', { name: 'Helping students succeed' }).click();
  await page.getByRole('button', { name: 'Seeing student progress' }).click();
  await page.getByRole('button', { name: 'Making a difference' }).click();
  await page.getByRole('button', { name: '✨ Generate with AI' }).click();
  await page.getByRole('button', { name: '✨ Generate with AI' }).click();
  await page.getByText('Act as a professional').press('ControlOrMeta+a');
  await page.getByText('Act as a professional').press('ControlOrMeta+c');
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'Continue to Persona' }).click();
  await page.getByRole('checkbox', { name: 'I have read and agree to the' }).click();
  await page.locator('.mt-0\\.5').first().click();
  await page.locator('div:nth-child(3) > .px-5 > .mt-0\\.5').click();
  await page.locator('div:nth-child(4) > .px-5 > .mt-0\\.5').click();
  await page.locator('div:nth-child(5) > .px-5 > .mt-0\\.5').click();
  await page.locator('div:nth-child(6) > .px-5 > .mt-0\\.5').click();
  await page.locator('div:nth-child(7) > .px-5 > .mt-0\\.5').click();
  await page.locator('div:nth-child(8) > .px-5 > .mt-0\\.5').click();
  await page.getByRole('checkbox', { name: 'I would like to receive' }).click();
  await page.getByRole('checkbox', { name: 'I give permission to feature' }).click();
  await page.getByRole('button', { name: 'Sign & Complete Registration' }).click();
  await page.getByRole('button', { name: 'Start Subject Assessments' }).click();
});